name: Workflow-Trial

on: [push]

jobs:

  Build-Test:
    runs-on: ubuntu-18.04

    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        python_pip_version:
          - "~= 20.2.4"
          - "~= 20.3.0"
          - "~= 21.0.0"
          - "~= 21.1.0"
          - "~= 21.2.0"
        python_setuptools_version:
          - "== 49.*"
          - "== 50.*"
          - "== 51.*"
          - "== 56.*"
          - "== 57.*"
        python_project_install_with_pip:
          - "false"
          - "true"
        python_project_test_with_pytest:
#         - "false"
          - "true"

    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: List files in the repository
        run: |
          find ${{ github.workspace }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            PYTHON_PIP_VERSION=${{ matrix.python_pip_version }}
            PYTHON_SETUPTOOLS_VERSION=${{ matrix.python_setuptools_version }}
            PYTHON_PROJECT_INSTALL_WITH_PIP=${{ matrix.python_project_install_with_pip }}
            PYTHON_PROJECT_TEST_WITH_PYTEST=${{ matrix.python_project_test_with_pytest }}
          load: true
          tags: local/python-pip-test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show image
        run: docker images

      - name: Inspect image
        run: docker image inspect local/python-pip-test

      - name: Run - Show pip version
        run: docker run -t local/python-pip-test pip --version

      - name: Run - List pip deps packages
        run: docker run -t local/python-pip-test pip list --not-required

      - name: Run - List Python packages (all)
        run: docker run -t local/python-pip-test pip list

      - name: Run - List Python packages (user)
        run: docker run -t local/python-pip-test pip list --user

      - name: Run - List Python packages (projects)
        run: docker run -t local/python-pip-test pip list --editable

      - name: Run - Check Python packages compatibility
        run: docker run -t local/python-pip-test pip check

      - name: Run - List Python packages dependencies
        run: docker run -t local/python-pip-test pipdeptree

      - name: Run - List Python packages dependencies
        run: docker run -t local/python-pip-test pipdeptree --exclude pip,pipdeptree,setuptools,wheel,chardet

      - name: Run - Exec project tests
        run: docker run -t local/python-pip-test
